version: '3.9'
services:
   backend:
    image: datalab-mi/${APP}-backend
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    environment:
     - http_proxy
     - https_proxy
     - no_proxy
     - PORT=${BACKEND_PORT}
     - PYTHONUNBUFFERED
     - RTSP_ADDR=${RTSP_ADDR}
     - MODEL_NAME_MOBILECOUNT
     - MODEL_NAME_DSNET
     - MODEL_NAME_MMCN
     - MODEL_TYPE
     - MODEL_TYPE_DETECTOR
     - FRAME_RATE
    command: ${COMMAND_PARAMS}
    volumes: # Add tmpfs filesystem to store rtsp image
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 21474836 #20Mo
          #mode: 700 # paranoid mode, acces to docker user only
      - ./models:/models/
networks:
  default:
    external:
      name: ${DC_NETWORK}
