version: '3.4'
services:
  nginx:
    image: datalab-mi/nginx-dev:${APP_VERSION}
    restart: always
    build:
      context: nginx
      target: production
      dockerfile: Dockerfile
      args:
        app_name: ${APP}
        app_ver: ${APP_VERSION}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    container_name: nginx
    environment:
      - APP
      - BACKEND_HOST
      - BACKEND_PORT
      - PORT
    ports:
      - "$PORT:80"
      #restart: always
    logging:
        #driver: none
        options:
          max-size: "10m"
          max-file: "1"
networks:
  default:
    external:
      name: ${DC_NETWORK}
