version: '3.4'
services:
   backend:
    image: datalab-mi/${APP}
    container_name: ${APP}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    environment:
     - http_proxy=${http_proxy}
     - https_proxy=${http_proxy}
     - no_proxy=${no_proxy}
     - APP_PORT=${APP_PORT}
     - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
     - RTSP_ADDR=${RTSP_ADDR}
    command: ${COMMAND_PARAMS}
