version: '3.4'
services:
   backend:
    image: datalab-mi/${APP}-backend
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    environment:
     - http_proxy
     - https_proxy
     - no_proxy
     - PORT=${BACKEND_PORT}
     - PYTHONUNBUFFERED
     - RTSP_ADDR=${RTSP_ADDR}
     - MODEL_NAME_DSNET
     - MODEL_NAME_MMCN
     - MODEL_TYPE
    command: ${COMMAND_PARAMS}

networks:
  default:
    external:
      name: ${DC_NETWORK}
