version: '3.4'

services:
  backend:
    volumes:
      - ./app:/app/
      - ./tests:/tests/
      - ./models:/models/
      - ./imgs:/imgs/
    ports:
      - "7000:80"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
     - LOG_LEVEL=info
