version: '3.4'

services:
  backend:
    volumes:
      - ./backend/app:/app/
      - ./backend/tests:/app/tests
      - ./models:/models/
      - ./imgs:/imgs/
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
     - LOG_LEVEL=info

networks:
  default:
    external:
      name: ${DC_NETWORK}
