name: CI for push // Test backend
on: [push]

jobs:
  check-files-modified:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_modified_files }}
    steps:
    - uses: actions/checkout@v2
    - name: Verify Changed files
      uses: tj-actions/changed-files@v18.4
      id: changed-files
      with:
        base_sha: ${{ github.event.pull_request.base.sha }}

  build-backend-and-test:
    runs-on: ubuntu-latest
    needs: check-files-modified
    if: ( contains(needs.check-files-modified.outputs.changed_files, 'backend/') )
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image for tests
      run: make backend-dev
    - name: Run tests
      run: make test
